name: bootjack
version: 0.5.3+1
author: Simon Pai <simonpai@rikulo.org>
description: |
  Bootjack is a porting of Bootstrap in Dart.
homepage: https://github.com/rikulo/dquery
documentation: http://blog.rikulo.org/posts/2013/May/General/bootjack-and-dquery/ 
dependencies:
  browser: any
  dquery: any
  rikulo_commons: any
