name: bootjack
version: 0.5.3
author: Simon Pai <simonpai@rikulo.org>
description: |
  Bootjack is a porting of Bootstrap in Dart.
homepage: http://rikulo.org/
dependencies:
  browser: any
  crypto: any
  dquery: '>=0.5.2'
  rikulo_commons: '>=0.7.3'
