name: bootjack
version: 0.6.0
author: Simon Pai <simonpai@rikulo.org>
description: |
  Bootjack is a porting of Twitter Bootstrap 3.0 in Dart.
homepage: http://rikulo.org/
dependencies:
  browser: any
  dquery: '>=0.5.2'
  rikulo_commons: '>=0.7.3'
