name: bootjack
version: 0.5.0
description: > 
  Bootjack is a porting of Bootstrap in Dart.
authors:
- Simon Pai <simonpai@rikulo.org>
homepage: http://rikulo.org/
dependencies:
  browser: any
  dquery: any
