name: bootjack
version: 0.5.2
description: > 
  Bootjack is a porting of Bootstrap in Dart.
authors:
- Simon Pai <simonpai@rikulo.org>
homepage: http://rikulo.org/
dependencies:
  browser: any
  dquery: '>=0.5.1'
  rikulo_commons: '>=0.7.3'
