name: bootjack
version: 0.5.0
description: > 
  Bootstrap ported to Dart world.
authors:
- Simon Pai <simonpai@rikulo.org>
homepage: http://rikulo.org/
dependencies:
  browser: any
  dquery:
    git:
      url: git://github.com/rikulo/dquery.git
